parameters:
  - name: DeployBranches
    displayName: Branches that should be deployed
    type: object
    default:
      - main

variables:
  BuildConfiguration: Release
  IsBranchDeployable: ${{ containsValue(parameters.DeployBranches, variables['Build.SourceBranchName']) }}
  AcrServiceConnection: s101d-datahub-spn-ees-dfe-gov-uk-docker-managed-service-connection

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
    - README.md

pr:
  - main

jobs:
  - job: BuildImageAndPushToAcr
    pool: ees-ubuntu2204-large
    workspace:
      clean: all
    steps:
      - task: Docker@2
        displayName: Build and push Screener API Docker image
        condition: and(succeeded(), eq(variables.IsBranchDeployable, true))
        inputs:
          containerRegistry: $(AcrServiceConnection)
          repository: ees-screener-api
          command: buildAndPush
          Dockerfile: Dockerfile
          tags: $(Build.BuildNumber)
        env:
          DOCKER_BUILDKIT: 1